name: Initialize

on:
  workflow_dispatch:
    inputs:
      company-name:
        description: "Company Name"
        required: true
      package-name:
        description: "Package Name"
        required: true

permissions:
  contents: write

jobs:
  call-local-rename-workflow:
    uses: ./.github/workflows/rename-package.yml
    with:
      company-name: ${{ inputs.company-name }}
      package-name: ${{ inputs.package-name }}
  
  initialize:
    runs-on: ubuntu-latest
    needs: [call-local-rename-workflow]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Remove and Clear Files
        run: |
          echo "Initializing README.md"
          echo "# ${{ inputs.package-name }}" > README.md
          
          echo "Initializing index.md"
          echo "# ${{ inputs.package-name }}" > README.md
          
          echo "Removing Example Project"
          find Runtime -type f ! -name '*.asmdef' -delete
          find Editor -type f ! -name '*.asmdef' -delete
          find Tests -type f ! -name '*.asmdef' -delete
          
          echo "Clearing documentation"
          find Documentation~/manual -type f ! -name 'getting-started.md' -delete
          find Documentation~/resources -type f ! -name '.nodoc' -delete
          
          echo "Removing '.meta' files"
          find . -name '*.meta' -type f -delete
          
          echo "Updating documentation url in package.json"
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1 | tr '[:upper:]' '[:lower:]')
          jq ".documentationUrl = \"$REPO_OWNER.github.io/$REPO_NAME\"" package.json > temp.json && mv temp.json package.json
          
          echo "Removing initialization workflow file"
          rm .github/workflows/initialize.yml

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: Initialized Package
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com